name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: pwsh

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'
        dir: '${{ github.workspace }}/qt/'
        modules: ''
        tools: 'tools_mingw,qt.tools.win32_mingw810'
        set-env: 'true'
    - name: make
      run: |
        pushd debug
        mingw32-make.exe SHELL=cmd
        popd
